# Generated by Django 6.0.1 on 2026-02-09 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reflection',
            name='week',
            field=models.CharField(default='2026-02', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_reflections', to=settings.AUTH_USER_MODEL),
        ),
    ]
