# Generated by Django 6.0.1 on 2026-02-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_message_options_message_seen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
