# Generated by Django 6.0.1 on 2026-02-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_message_post_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exchange_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
