# Generated by Django 6.0.1 on 2026-03-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_message_request_from'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeReview',
        ),
    ]
