# Generated by Django 6.0.1 on 2026-03-15 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
