# Generated by Django 6.0.1 on 2026-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.IntegerField(default=0),
        ),
    ]
